version: "3.8"

services:
  db_postgres_fastapi:
    image: "postgres"
    container_name: db_postgres_fastapi
    ports:
      - "7000:5432"
      - "9000:5434"
    env_file:
      - "./database.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: app
    volumes:
      - static:/code/static
      - .:/code
    expose:
      - 8000
    ports:
      - 5432:8000
      - 5434:8000
    env_file:
      - "./database.env"
    depends_on:
      - db_postgres_fastapi

volumes:
  .:
  postgres_data:
  static:
